@startuml
actor "Player" as A1
actor "Time" as A2

rectangle "Tower Dynasty" {
    usecase "Play round" as UC1
    usecase "Show current items" as UC2
    usecase "View inventory" as UC3
    usecase "Buy item" as UC4
    usecase "Break tower" as UC5
    usecase "Pick towers" as UC6
    usecase "Upgrade towers" as UC7
    usecase "Go to shop" as UC8
    usecase "Update money" as UC9
}

A1 -- UC1
A1 -- UC3
A1 -- UC6

A2 -- UC1
@enduml