@startuml
'https://plantuml.com/use-case-diagram

actor "Player" as A1

rectangle "Tower Dynasty" {
    usecase "Setup game" as UC1
    usecase "Play round" as UC2
    usecase "Shop" as UC3
    usecase "Inventory" as UC4
}

A1 --> UC1
A1 --> UC2
A1 --> UC3
A1 --> UC4
@enduml